### ISSUE TITLE
Add comments of function

### ISSUE THREAD

**Issue by leico** [2bbb/ofxJsonUtils#12]
Hello @2bbb, thank you to create useful addon.
I am trying to create a app, then I write a comments of function features like:

https://github.com/leico/ofxJsonUtils/commit/f6047699e8cc665168c50ce154819f1cf7905373

How about this? If you like, I will create a pull request.
Yes, if I misunderstood features, you can fix those comments in pull request.  
Thanks to read.

**Comment by 2bbb** [comment]
@leico 

i agree to add comments.
but i think your comments are incomplete.
and i don't like your style of comments and separating scope resolution operator with space.

thanks.
