### ISSUE TITLE
not compiling on Windows(of098, VS2015)

### ISSUE THREAD

**Issue by nariakiiwatani** [2bbb/ofxJsonUtils#8]
minimum code that reproduces the issue
> struct Hoge { ofJson toJson() const {return 0;} } hoge;
> ofxJsonUtils::create("hoge",hoge);

will make error below.
> 'bbb::json_utils::detail::has_toJson<const type>::Test': ambiguous call to overloaded function	jsonutilstest	

If I commented out one of these 2 declarations, it builds.
> template <typename C> static std::true_type Test(really_has<ofJson (C::*)() const, &C::toJson> *);
> template <typename C> static std::true_type Test(really_has<ofJson (C::*)(), &C::toJson> *);

**Comment by 2bbb** [comment]
thank you for report.

i will check it!

**Comment by 2bbb** [comment]
@nariakiiwatani 

please check [this branch](https://github.com/2bbb/ofxJsonUtils/tree/bugfix/has_method)!

**Comment by nariakiiwatani** [comment]
fantastic!
